version: "3"
services:
  app:
    hostname: imgfiltrate.hub
    build: ./app
    ports:
      - 3200:80
    restart: always
    environment:
      TOKEN: ${TOKEN:-super_secret_token}
  bot:
    build: ./bot
    ports:
      - 3201:8000
    privileged: true
    restart: always
    environment:
      TOKEN: ${TOKEN:-super_secret_token}
